services:
  azdo-runner-1:
    build: .
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-1
      AZP_WORK: /azp/_work
      AGENT_ALLOW_RUNASROOT: "1"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f Agent.Listener >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /azp/_work:/azp/_work

  azdo-runner-2:
    build: .
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-2
      AZP_WORK: /azp/_work
      AGENT_ALLOW_RUNASROOT: "1"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f Agent.Listener >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /azp/_work:/azp/_work
