services:
  azdo-runner-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-1
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-2
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-3
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-4:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-4
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-5:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-5
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-6:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-6
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-7:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-7
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-8:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-8
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-9:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-9
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"

  azdo-runner-10:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AZP_URL: ${AZP_URL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: ${AZP_POOL}
      AZP_AGENT_NAME: office-runner-10
      AZP_WORK: _work
      AGENT_ALLOW_RUNASROOT: "1"
